In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.DataFrame({"text":["people watch praneshnikhar",
                           "pranesh is ai engineer",
                           "pranesh loves coding",
                           "pranesh lives in jaipur"],"output":[1,1,0,0]})

df

text  output
0  people watch praneshnikhar       1
1      pranesh is ai engineer       1
2        pranesh loves coding       0
3     pranesh lives in jaipur       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
print(cv.vocabulary_)

{'people': 8, 'watch': 11, 'praneshnikhar': 10, 'pranesh': 9, 'is': 4, 'ai': 0, 'engineer': 2, 'loves': 7, 'coding': 1, 'lives': 6, 'in': 3, 'jaipur': 5}


In [ ]:
bow.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0]])

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 0 0 0 0 0 1 0 1 1]]
[[1 0 1 0 1 0 0 0 0 1 0 0]]
[[0 1 0 0 0 0 0 1 0 1 0 0]]


In [ ]:
cv.transform(['praneh is ai engineer']).toarray()

array([[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
X  = bow.toarray()
y = df['output']

In [ ]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
print(cv.vocabulary_)

{'people watch': 5, 'watch praneshnikhar': 9, 'pranesh is': 6, 'is ai': 2, 'ai engineer': 0, 'pranesh loves': 8, 'loves coding': 4, 'pranesh lives': 7, 'lives in': 3, 'in jaipur': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 0 0 1 0 0 0 1]]
[[1 0 1 0 0 0 1 0 0 0]]
[[0 0 0 0 1 0 0 0 1 0]]


## **TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [ ]:
arr = tfid.fit_transform(df['text']).toarray()

In [ ]:
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.57735027, 0.57735027],
       [0.5417361 , 0.        , 0.5417361 , 0.        , 0.5417361 ,
        0.        , 0.        , 0.        , 0.        , 0.34578314,
        0.        , 0.        ],
       [0.        , 0.64450299, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.64450299, 0.        , 0.41137791,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.5417361 , 0.        ,
        0.5417361 , 0.5417361 , 0.        , 0.        , 0.34578314,
        0.        , 0.        ]])

In [ ]:
print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.22314355 1.91629073 1.91629073]
